Send("#r")
WinWaitActive("Run")
Send("cmd.exe{ENTER}")
WinWaitActive("C:\WINDOWS\system32\cmd.exe")
Send("whoami{ENTER}")
Send("ipconfig /all{ENTER}")
Send("ping -n 8.8.8.8{ENTER}")
Send("systeminfo{ENTER}")
Send("dir c:\Users{ENTER}")
Send("netstat -ano{ENTER}")
Send("net user{ENTER}")
Send("tasklist{ENTER}")
Send("exit{ENTER}")
